import  { Component } from 'react';

export class Counter extends Component{
      constructor(props){
        super(props);
        this.state={
            ctr:0
        }
        this.incrementCtr = this.incrementCtr.bind(this)
      } 
      
     incrementCtr(){
        console.log("invoked")
        this.setState({ctr:this.state.ctr+1})

     } 

    render(){
            return(
                <div>
                    <h4>This is a view generated by class component</h4>
                    
                     <button onClick= {this.incrementCtr }>click me</button>
                     <button onClick= {()=>this.setState({ctr:this.state.ctr+1}) }>lambda fun click me</button>
                     <h5> You clicked for {this.state.ctr} times</h5>
                </div>
            )  

    }


}